### ISSUE TITLE
PGI: Unwanted Changes in E. Project Deliverables Section

### ISSUE THREAD

**Issue by thirdygayares** [SVFC-Travel-Booking-System/Travel-booking-System_Documentation#6]
Please remove all the changes made in the E. Project Deliverables section. This section is meant to be a summary of the documentation in PGI and should not contain any information

**Comment by jhayr311231** [comment]
Removed unwanted Info on PGI

<img width="462" alt="image" src="https://github.com/user-attachments/assets/3b18a99f-51f5-4007-936c-5e7025245a7b">

**Comment by jhayr311231** [comment]
Removed unwanted Info on PGI
![image](https://github.com/user-attachments/assets/75e47b91-7cef-4c39-9feb-fa28444797ba)
